name: Build Lakos OS

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y nasm gcc-multilib binutils

      - name: Compile OS
        run: |
          # Используем твой Makefile
          make

      - name: Upload Kernel Binary
        uses: actions/upload-artifact@v3
        with:
          name: lakos-kernel
          path: lakos.bin
