name: Build and Release

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          # Устанавливаем поддержку x86 и инструменты бинарных файлов
          sudo apt-get install -y gcc-multilib nasm make binutils binutils-i686-linux-gnu
          
          # Делаем симлинки для компилятора и линковщика
          # Чтобы Makefile думал, что работает с i686-elf инструментами
          sudo ln -s /usr/bin/gcc /usr/bin/i686-elf-gcc
          sudo ln -s /usr/bin/ld /usr/bin/i686-elf-ld

      - name: Build Kernel
        run: make

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.run_number }}
          name: "Lakos OS Build ${{ github.run_number }}"
          body: "Автоматическая сборка ядра. Файл lakos.bin готов."
          draft: false
          prerelease: false
          files: lakos.bin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
