name: Build Lakos OS

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          # gcc-multilib нужен для сборки 32-бит на 64-битной системе
          # binutils предоставляет ld
          sudo apt-get install -y nasm gcc-multilib binutils build-essential

      - name: Compile OS
        run: |
          # Если в твоем Makefile жестко прописан i686-elf-gcc, 
          # мы заменим его на обычный gcc с флагом -m32
          make CC="gcc -m32" LD="ld -m elf_i386"

      - name: Upload Kernel Binary
        uses: actions/upload-artifact@v4
        with:
          name: lakos-kernel
          path: lakos.bin
