name: Build and Release

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Разрешение на создание релизов и тегов

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-multilib nasm make binutils binutils-i686-linux-gnu
          sudo ln -s /usr/bin/gcc /usr/bin/i686-elf-gcc
          sudo ln -s /usr/bin/ld /usr/bin/i686-elf-ld

      - name: Build Kernel and iso
        run: make iso

      # Создание релиза с номером текущего Workflow Run
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          # github.run_number — это и есть номер запуска (1, 2, 3...)
          tag_name: "LKB-${{ github.run_number }}"
          name: "Lakos OS Build #${{ github.run_number }}"
          body: |
            Это автоматическая сборка №${{ github.run_number }}.
            Системный ID запуска: ${{ github.run_id }}
          files: lakos.bin, lakos.iso
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
