name: Build Lakos OS

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Обновлено до v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y nasm gcc-multilib binutils

      - name: Compile OS
        run: |
          # Собираем ядро и FS через твой Makefile
          make

      - name: Upload Kernel Binary
        uses: actions/upload-artifact@v4 # ИСПРАВЛЕНО: теперь версия v4
        with:
          name: lakos-kernel
          path: lakos.bin

      - name: Upload InitRD
        uses: actions/upload-artifact@v4 # ИСПРАВЛЕНО: теперь версия v4
        with:
          name: lakos-initrd
          path: modules.tar
