name: Build and Release

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Разрешение на создание релизов

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-multilib nasm make binutils

      - name: Build Kernel
        run: make

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.run_number }}
          name: "Lakos OS Build ${{ github.run_number }}"
          body: "Автоматическая сборка ядра. Файл lakos.bin прикреплен ниже."
          draft: false
          prerelease: false
          files: lakos.bin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
