name: Build Kernel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-multilib nasm make binutils

    - name: Compile OS
      run: make

    # ШАГ ДЛЯ АВТО-РЕЛИЗА
    - name: Create Release
      if: github.ref == 'refs/heads/main' # Делать релиз только при пуше в main
      uses: softprops/action-gh-release@v1
      with:
        tag_name: "latest-build"
        name: "Lakos OS Nightly Build"
        draft: false
        prerelease: true
        files: |
          lakos.bin
          # Сюда можно добавить и .iso, если ты его генерируешь
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
