name: Build and Release

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          # Устанавливаем поддержку 32-бит для стандартного gcc
          sudo apt-get install -y gcc-multilib nasm make binutils
          
          # Трюк: создаем "подделку" i686-elf-gcc, указывающую на обычный gcc
          # Это позволит твоему Makefile работать без правок
          sudo ln -s /usr/bin/gcc /usr/bin/i686-elf-gcc

      - name: Build Kernel
        run: make

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.run_number }}
          name: "Lakos OS Build ${{ github.run_number }}"
          body: "Автоматический релиз ядра Lakos. Файл lakos.bin готов к запуску."
          draft: false
          prerelease: false
          files: lakos.bin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
