- name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        if: github.ref == 'refs/heads/main' # Делать релиз только при пуше в main
        with:
          tag_name: "latest-build"
          name: "Lakos OS Nightly Build"
          body: "Автоматическая сборка ядра Lakos. Коммит: ${{ github.sha }}"
          draft: false
          prerelease: false
          files: |
            lakos.bin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
